{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "crypto-scalper-bot.fullname" . }}
  labels:
    {{- include "crypto-scalper-bot.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "crypto-scalper-bot.tradingBot.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      interval: {{ .Values.monitoring.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.monitoring.serviceMonitor.scrapeTimeout }}
      path: /metrics
{{- end }}
